In [18]:
import torch
import torchvision

In [2]:
torch.rand(3)

tensor([0.5546, 0.9435, 0.0770])

In [3]:
torch.rand(3).shape

torch.Size([3])

In [4]:
torch.rand(16, 17)

tensor([[0.5371, 0.1690, 0.3596, 0.3989, 0.8953, 0.0299, 0.7732, 0.6926, 0.0990,
         0.4775, 0.2200, 0.2720, 0.3820, 0.1534, 0.5185, 0.1563, 0.5680],
        [0.3323, 0.8861, 0.2452, 0.8694, 0.8614, 0.9657, 0.0827, 0.1938, 0.0443,
         0.5317, 0.9323, 0.9425, 0.3853, 0.7308, 0.2982, 0.5843, 0.1785],
        [0.2934, 0.3555, 0.2063, 0.5336, 0.0128, 0.5093, 0.9147, 0.2682, 0.5082,
         0.9848, 0.0760, 0.3013, 0.8301, 0.4832, 0.3341, 0.6039, 0.5995],
        [0.2497, 0.0624, 0.2028, 0.7540, 0.4350, 0.7880, 0.5190, 0.6501, 0.6882,
         0.4653, 0.4119, 0.7885, 0.0072, 0.0084, 0.8512, 0.1035, 0.4752],
        [0.7572, 0.6110, 0.2167, 0.4483, 0.7393, 0.8103, 0.8155, 0.8665, 0.7357,
         0.6308, 0.7419, 0.4158, 0.2715, 0.9859, 0.7734, 0.3698, 0.5620],
        [0.4260, 0.2487, 0.5604, 0.0417, 0.8273, 0.3643, 0.1883, 0.8318, 0.4421,
         0.9134, 0.8055, 0.0116, 0.2669, 0.3351, 0.7620, 0.2168, 0.4174],
        [0.2172, 0.5604, 0.7489, 0.6035, 0.2738, 0.5359, 0.7765, 0.758

In [5]:
torch.rand(16, 17).shape

torch.Size([16, 17])

In [6]:
torch.rand(1, 2, 3, 4, 5)

tensor([[[[[7.3903e-01, 3.1320e-01, 7.3773e-01, 8.5491e-01, 7.9430e-02],
           [2.0297e-01, 5.9903e-01, 2.1045e-01, 5.2806e-01, 9.1031e-01],
           [7.6002e-04, 3.3622e-02, 6.5161e-01, 6.7415e-02, 9.4116e-01],
           [5.7940e-01, 3.4861e-01, 8.9440e-01, 1.2270e-02, 3.7418e-01]],

          [[7.1114e-01, 9.9024e-01, 7.3143e-01, 8.0690e-01, 9.5182e-01],
           [3.0765e-01, 9.1006e-01, 2.1315e-01, 8.1658e-01, 6.8787e-01],
           [6.8659e-01, 7.4333e-01, 6.9513e-02, 5.0373e-01, 9.1259e-01],
           [5.0172e-03, 8.4318e-01, 2.9568e-01, 5.8871e-01, 4.3935e-01]],

          [[4.2310e-01, 9.1872e-01, 9.3356e-01, 3.2926e-01, 7.7271e-01],
           [4.9671e-01, 1.4979e-01, 1.9485e-04, 3.2715e-01, 4.0700e-01],
           [9.1633e-01, 8.5056e-01, 2.8296e-01, 6.6848e-01, 2.1668e-01],
           [3.0511e-01, 4.3597e-01, 5.9667e-01, 1.8890e-01, 2.0637e-01]]],


         [[[2.1754e-01, 3.6264e-01, 3.6609e-01, 4.1736e-01, 6.2938e-01],
           [4.6772e-01, 5.0641e-01, 1.0074e

In [7]:
torch.rand(1, 2, 3, 4, 5).shape

torch.Size([1, 2, 3, 4, 5])

In [8]:
a = torch.rand(5, 12)
b = torch.rand(12, 16)

In [10]:
a.shape, b.shape

(torch.Size([5, 12]), torch.Size([12, 16]))

In [11]:
a * b # Element-wise multiplication

RuntimeError: The size of tensor a (12) must match the size of tensor b (16) at non-singleton dimension 1

In [13]:
c = a @ b

In [14]:
c.shape

torch.Size([5, 16])

In [15]:
c = b @ a

RuntimeError: mat1 and mat2 shapes cannot be multiplied (12x16 and 5x12)

In [16]:
c = b.T @ a.T

In [17]:
c.shape

torch.Size([16, 5])

In [19]:
# MNIST : hello world
# EMNIST : extended with letters in addition to digits
# KMNIST : Kuzushiji, Japanese characters
# QMNIST : newer MNIST with better source information

data_path = "../data/"

mnist_transforms = torchvision.transforms.Compose(
    [
        torchvision.transforms.ToTensor(),
        torchvision.transforms.Normalize((0.1307,), (0.3081,)),
    ]
)

train_dataset = torchvision.datasets.MNIST(
    root=data_path, train=True, download=True, transform=mnist_transforms
)

/opt/mambaforge/envs/cs152/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /tmp/pip-req-build-pma2oi4d/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [24]:
train_dataset

Dataset MNIST
    Number of datapoints: 60000
    Root location: ../data/
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.1307,), std=(0.3081,))
           )

In [25]:
train_dataset.data[0]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
          18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   

In [27]:
train_loader = torch.utils.data.DataLoader(train_dataset)

In [28]:
for (image, label) in train_loader:
    print(image.shape, label.shape)
    break

torch.Size([1, 1, 28, 28]) torch.Size([1])
