In [67]:
from random import shuffle
import torch

In [6]:
dataset = [
    ("The dog ate the apple".lower().split(), ["D", "N", "V", "D", "N"]),
    ("Everybody read that book".lower().split(), ["N", "V", "D", "N"]),
    ("Trapp is sleeping".lower().split(), ["N", "V", "V"]),
    ("Everybody ate the apple".lower().split(), ["N", "V", "D", "N"]),
    ("Cats are good".lower().split(), ["N", "V", "D"]),
    ("Dogs are not as good as cats".lower().split(),["N", "V", "D", "D", "D", "D", "N"]),
    ("Dogs eat dog food".lower().split(), ["N", "V", "N", "N"]),
    ("Watermelon is the best food".lower().split(), ["N", "V", "D", "D", "N"]),
    ("I want a milkshake right now".lower().split(), ["N", "V", "D", "N", "D", "D"]),
    ("I have too much homework".lower().split(), ["N", "V", "D", "D", "N"]),
    ("Zoom won't work".lower().split(), ["N", "D", "V"]),
    ("Pie also sounds good".lower().split(), ["N", "D", "V", "D"]),
    ("The college is having the department fair this Friday".lower().split(),["D", "N", "V", "V", "D", "N", "N", "D", "N"]),
    ("Research interests span many areas".lower().split(), ["N", "N", "V", "D", "N"]),
    ("Alex is finishing his Ph.D".lower().split(), ["N", "V", "V", "D", "N"]),
    ("She is the author".lower().split(), ["N", "V", "D", "N"]),
    ("It is almost the end of the semester".lower().split(), ["N", "V", "D", "D", "N", "D", "D", "N"]),
    ("Blue is a color".lower().split(), ["N", "V", "D", "N"]),
    ("They wrote a book".lower().split(), ["N", "V", "D", "N"]),
    ("The syrup covers the pancake".lower().split(), ["D", "N", "V", "D", "N"]),
    ("Harrison has these teeth".lower().split(), ["N", "V", "D", "N"]),
    ("The numbers are fractions".lower().split(), ["D", "N", "V", "N"]),
    ("Yesterday happened".lower().split(), ["N", "V"]),
    ("Caramel is sweet".lower().split(), ["N", "V", "D"]),
    ("Computers use electricity".lower().split(), ["N", "V", "N"]),
    ("Gold is a valuable thing".lower().split(), ["N", "V", "D", "D", "N"]),
    ("This extension cord helps".lower().split(), ["D", "D", "N", "V"]),
    ("It works on my machine".lower().split(), ["N", "V", "D", "D", "N"]),
    ("We have the words".lower().split(), ["N", "V", "D", "N"]),
    ("Trapp is a dog".lower().split(), ["N", "V", "D", "N"]),
    ("This is a computer".lower().split(), ["N", "V", "D", "N"]),
    ("I love lamps".lower().split(), ["N", "V", "N"]),
    ("I walked outside".lower().split(), ["N", "V", "N"]),
    ("You never bike home".lower().split(), ["N", "D", "V", "N"]),
    ("You are a wizard Harry".lower().split(), ["N", "V", "D", "N", "N"]),
    ("Trapp ate the shoe".lower().split(), ["N", "V", "D", "N"]),
    ("Jett failed his test".lower().split(), ["N", "V", "D", "N"]),
    ("Alice won the game".lower().split(), ["N", "V", "D", "N"]),
    ("The class lasted a semester".lower().split(), ["D", "N", "V", "D", "N"]),
    ("The tree had a branch".lower().split(), ["D", "N", "V", "D", "N"]),
    ("I ran a race".lower().split(), ["N", "V", "D", "N"]),
    ("The dog barked".lower().split(), ["D", "N", "V"]),
    ("Toby hit the wall".lower().split(), ["N", "V", "D", "N"]),
    ("Zayn ate an apple".lower().split(), ["N", "V", "D", "N"]),
    ("The cat fought the dog".lower().split(), ["D", "N", "V", "D", "N"]),
    ("I got an A".lower().split(), ["N", "V", "D", "N"]),
    ("The A hurt".lower().split(), ["D", "N", "V"]),
    ("I jump".lower().split(), ["N", "V"]),
    ("I drank a yerb".lower().split(), ["N", "V", "D", "N"]),
    ("The snake ate a fruit".lower().split(), ["D", "N", "V", "D", "N"]),
    ("I played the game".lower().split(), ["N", "V", "D", "N"]),
    ("I watched a movie".lower().split(), ["N", "V", "D", "N"]),
    ("Clark fixed the audio".lower().split(), ["N", "V", "D", "N"]),
    ("I went to Frary".lower().split(), ["N", "V", "D", "N"]),
    ("I go to Pomona".lower().split(), ["N", "V", "D", "N"]),
    ("Food are friends not fish".lower().split(), ["N", "V", "N", "D", "N"]),
    ("You are reading this".lower().split(), ["N", "V", "D", "N"]),
    ("Wonderland protocol is amazing".lower().split(), ["D", "N", "V", "D"]),
    ("This is a sentence".lower().split(), ["D", "V", "D", "N"]),
    ("I should be doing homework".lower().split(), ["N", "V", "V", "V", "N"]),
    ("Computers are tools".lower().split(), ["N", "V", "N"]),
    ("The whale swims".lower().split(), ["D", "N", "V"]),
    ("A cup is filled".lower().split(), ["D", "N", "V", "V"]),
    ("This is a cat".lower().split(), ["D", "V", "D", "N"]),
    ("These are trees".lower().split(), ["D", "V", "N"]),
    ("The cat is the teacher".lower().split(), ["D", "N", "V", "D", "N"]),
    ("I ate food today".lower().split(), ["N", "V", "N", "N"]),
    ("I am a human".lower().split(), ["N", "V", "D", "N"]),
    ("The cat sleeps".lower().split(), ["D", "N", "V"]),
    ("Whales are mammals".lower().split(), ["N", "V", "N"]),
    ("I like turtles".lower().split(), ["N", "V", "N"]),
    ("A shark ate me".lower().split(), ["D", "N", "V", "N"]),
]

# There are mirrors	D, V, N
# The bus spins	D, N, V
# Computers are machines	N, V, N

In [7]:
word_to_index = {}
total_words = 0

tag_to_index = {}
tag_list = []
total_tags = 0

for sentence, tags in dataset:
    assert len(sentence) == len(tags)
    total_words += len(sentence)
    for word in sentence:
        if word not in word_to_index:
            word_to_index[word] = len(word_to_index)

    total_tags += len(tags)
    for tag in tags:
        if tag not in tag_to_index:
            tag_to_index[tag] = len(tag_to_index)
            tag_list.append(tag)

In [8]:
print("       Vocabulary Indices")
print("-------------------------------")

for word in sorted(word_to_index):
    print(f"{word:>14} => {word_to_index[word]:>2}")

print("\nTotal number of words:", total_words)
print("Number of unique words:", len(word_to_index))

       Vocabulary Indices
-------------------------------
             a => 23
          alex => 48
         alice => 106
        almost => 55
          also => 35
            am => 160
       amazing => 147
            an => 121
         apple =>  3
           are => 12
         areas => 47
            as => 16
           ate =>  2
         audio => 136
        author => 53
        barked => 116
            be => 150
          best => 20
          bike => 98
          blue => 59
          book =>  7
        branch => 113
       caramel => 74
           cat => 122
          cats => 11
         clark => 134
         class => 109
       college => 37
         color => 60
      computer => 91
     computers => 76
          cord => 83
        covers => 64
           cup => 155
    department => 39
           dog =>  1
          dogs => 14
         doing => 151
         drank => 127
           eat => 17
   electricity => 78
           end => 56
     everybody =>  4
     extension => 82
    

In [9]:
print("Tag Indices")
print("-----------")

for tag, index in tag_to_index.items():
    print(f"  {tag} => {index}")

print("\nTotal number of tags:", total_tags)
print("Number of unique tags:", len(tag_to_index))

Tag Indices
-----------
  D => 0
  N => 1
  V => 2

Total number of tags: 299
Number of unique tags: 3


In [10]:
def convert_words_to_index_tensor(words, mapping):
    indices = [mapping[w] for w in words]
    return torch.tensor(indices, dtype=torch.long)

In [14]:
vocab_size = len(word_to_index)  # Depends on the dataset
embed_dim = 6  # Hyperparameter

example_sentence = ["dog", "ate"]
example_sentence_indices = convert_words_to_index_tensor(example_sentence, word_to_index)

embedding_layer = torch.nn.Embedding(vocab_size, embed_dim)
embeddings = embedding_layer(example_sentence_indices)

embeddings.shape, embeddings

(torch.Size([2, 6]),
 tensor([[ 1.3938,  0.4583, -0.7672, -1.2876,  1.1449,  1.3219],
         [-1.1509,  0.3885, -0.4995, -0.8855,  1.0855,  0.5448]],
        grad_fn=<EmbeddingBackward>))

In [20]:
state_dim = 4  # Hyperparamter
num_layers = 4 # Hyperparameter

lstm_layer = torch.nn.LSTM(embed_dim, state_dim, num_layers=num_layers, batch_first=True)

# We can ignore the hidden and cell state outputs
lstm_output, (h_T, C_T) = lstm_layer(embeddings.unsqueeze(0))
lstm_output.shape, lstm_output

(torch.Size([1, 2, 4]),
 tensor([[[-0.0900, -0.0537,  0.0928, -0.0771],
          [-0.1454, -0.0688,  0.1296, -0.1164]]], grad_fn=<TransposeBackward0>))

In [62]:
linear_layer = torch.nn.Linear(state_dim, tag_size)
linear_output = linear_layer(lstm_output)
linear_output.shape, linear_output

(torch.Size([1, 2, 3]),
 tensor([[[-0.4539, -0.2122, -0.5056],
          [-0.4318, -0.2250, -0.5311]]], grad_fn=<AddBackward0>))

In [89]:
class NN_LSTM(torch.nn.Module):
    def __init__(self, vocab_size, embed_dim, state_dim, num_layers, tag_size):
        super().__init__()
        self.embed = torch.nn.Embedding(vocab_size, embed_dim)
        self.lstm = torch.nn.LSTM(embed_dim, state_dim, num_layers=num_layers, batch_first=True)
        self.linear = torch.nn.Linear(state_dim, tag_size)
    
    def forward(self, X):
        X = self.embed(X)
        X, _ = self.lstm(X)
        return self.linear(X)

In [90]:
vocab_size = len(word_to_index)
embed_dim = 6
state_dim = 4
num_layers = 2
tag_size = len(tag_to_index)

model = NN_LSTM(vocab_size, embed_dim, state_dim, num_layers, tag_size)

In [91]:
x = convert_words_to_index_tensor(example_sentence, word_to_index)
yhat = model(x.unsqueeze(0))

yhat.shape, yhat

(torch.Size([1, 2, 3]),
 tensor([[[ 0.0020, -0.0391,  0.1059],
          [ 0.0156, -0.0201,  0.1081]]], grad_fn=<AddBackward0>))

In [64]:
# Hyperparameters
embed_dim = 6
state_dim = 4
num_layers = 2

valid_percent = 0.2
learning_rate = 0.1
num_epochs = 300

In [68]:
# Dataset values
N = len(dataset)
vocab_size = len(word_to_index)
tag_size = len(tag_to_index)

# Shuffle the data so that we can split the dataset randomly
shuffle(dataset)

split_point = int(N * valid_percent)
valid_dataset = dataset[:split_point]
train_dataset = dataset[split_point:]

len(valid_dataset), len(train_dataset)

(14, 58)

In [115]:
def compute_accuracy(dataset, word_map, tag_map):
    """A helper function for computing accuracy on the given dataset."""
    total_words = 0
    total_correct = 0
    
    model.eval()

    with torch.no_grad():
        for sentence, tags in dataset:
            sentence_indices = convert_words_to_index_tensor(sentence, word_map)
            tag_scores = model(sentence_indices.unsqueeze(0))
            predictions = tag_scores.argmax(dim=1)
            total_words += len(sentence)
            print('tags', tags, predictions.shape)
            print([p.item() for p in predictions.squeeze()])
            total_correct += sum(t == tag_list[p.item()] for t, p in zip(tags, predictions.squeeze()))

    return total_correct / total_words

In [116]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

accuracy = compute_accuracy(valid_dataset, word_to_index, tag_to_index)
print(f"Validation accuracy before training : {accuracy * 100:.2f}%")

for epoch in range(num_epochs):
    # Shuffle the data for each epoch (stochastic gradient descent)
    shuffle(train_dataset)
    
    for sentence, tags in train_dataset:

        model.zero_grad()

        sentence = convert_to_indices_tensor(sentence, word_indices)
        tags = convert_to_indices_tensor(tags, tag_indices)
        
        tag_scores = model(sentence)
        
        loss = criterion(tag_scores, tags)
        
        loss.backward()
        optimizer.step()

accuracy = compute_accuracy(valid_dataset)
print(f"Validation accuracy after training  : {accuracy * 100:.2f}%")

tags ['N', 'V', 'N'] torch.Size([1, 3])
[2, 1, 2]
tags ['N', 'V', 'D', 'N'] torch.Size([1, 3])
[3, 3, 3]


IndexError: list index out of range